# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kazax/Delta-Script

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kazax/Delta-Script

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kazax/Delta-Script/CMakeFiles /home/kazax/Delta-Script//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kazax/Delta-Script/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named delta_vm

# Build rule for target.
delta_vm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 delta_vm
.PHONY : delta_vm

# fast build rule for target.
delta_vm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/build
.PHONY : delta_vm/fast

src/executing/core-api.o: src/executing/core-api.c.o
.PHONY : src/executing/core-api.o

# target to build an object file
src/executing/core-api.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/executing/core-api.c.o
.PHONY : src/executing/core-api.c.o

src/executing/core-api.i: src/executing/core-api.c.i
.PHONY : src/executing/core-api.i

# target to preprocess a source file
src/executing/core-api.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/executing/core-api.c.i
.PHONY : src/executing/core-api.c.i

src/executing/core-api.s: src/executing/core-api.c.s
.PHONY : src/executing/core-api.s

# target to generate assembly for a file
src/executing/core-api.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/executing/core-api.c.s
.PHONY : src/executing/core-api.c.s

src/executing/debug.o: src/executing/debug.c.o
.PHONY : src/executing/debug.o

# target to build an object file
src/executing/debug.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/executing/debug.c.o
.PHONY : src/executing/debug.c.o

src/executing/debug.i: src/executing/debug.c.i
.PHONY : src/executing/debug.i

# target to preprocess a source file
src/executing/debug.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/executing/debug.c.i
.PHONY : src/executing/debug.c.i

src/executing/debug.s: src/executing/debug.c.s
.PHONY : src/executing/debug.s

# target to generate assembly for a file
src/executing/debug.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/executing/debug.c.s
.PHONY : src/executing/debug.c.s

src/executing/exec.o: src/executing/exec.c.o
.PHONY : src/executing/exec.o

# target to build an object file
src/executing/exec.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/executing/exec.c.o
.PHONY : src/executing/exec.c.o

src/executing/exec.i: src/executing/exec.c.i
.PHONY : src/executing/exec.i

# target to preprocess a source file
src/executing/exec.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/executing/exec.c.i
.PHONY : src/executing/exec.c.i

src/executing/exec.s: src/executing/exec.c.s
.PHONY : src/executing/exec.s

# target to generate assembly for a file
src/executing/exec.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/executing/exec.c.s
.PHONY : src/executing/exec.c.s

src/executing/loader/check.o: src/executing/loader/check.c.o
.PHONY : src/executing/loader/check.o

# target to build an object file
src/executing/loader/check.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/executing/loader/check.c.o
.PHONY : src/executing/loader/check.c.o

src/executing/loader/check.i: src/executing/loader/check.c.i
.PHONY : src/executing/loader/check.i

# target to preprocess a source file
src/executing/loader/check.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/executing/loader/check.c.i
.PHONY : src/executing/loader/check.c.i

src/executing/loader/check.s: src/executing/loader/check.c.s
.PHONY : src/executing/loader/check.s

# target to generate assembly for a file
src/executing/loader/check.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/executing/loader/check.c.s
.PHONY : src/executing/loader/check.c.s

src/executing/loader/load.o: src/executing/loader/load.c.o
.PHONY : src/executing/loader/load.o

# target to build an object file
src/executing/loader/load.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/executing/loader/load.c.o
.PHONY : src/executing/loader/load.c.o

src/executing/loader/load.i: src/executing/loader/load.c.i
.PHONY : src/executing/loader/load.i

# target to preprocess a source file
src/executing/loader/load.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/executing/loader/load.c.i
.PHONY : src/executing/loader/load.c.i

src/executing/loader/load.s: src/executing/loader/load.c.s
.PHONY : src/executing/loader/load.s

# target to generate assembly for a file
src/executing/loader/load.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/executing/loader/load.c.s
.PHONY : src/executing/loader/load.c.s

src/executing/sym.o: src/executing/sym.c.o
.PHONY : src/executing/sym.o

# target to build an object file
src/executing/sym.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/executing/sym.c.o
.PHONY : src/executing/sym.c.o

src/executing/sym.i: src/executing/sym.c.i
.PHONY : src/executing/sym.i

# target to preprocess a source file
src/executing/sym.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/executing/sym.c.i
.PHONY : src/executing/sym.c.i

src/executing/sym.s: src/executing/sym.c.s
.PHONY : src/executing/sym.s

# target to generate assembly for a file
src/executing/sym.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/executing/sym.c.s
.PHONY : src/executing/sym.c.s

src/executing/user-api.o: src/executing/user-api.c.o
.PHONY : src/executing/user-api.o

# target to build an object file
src/executing/user-api.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/executing/user-api.c.o
.PHONY : src/executing/user-api.c.o

src/executing/user-api.i: src/executing/user-api.c.i
.PHONY : src/executing/user-api.i

# target to preprocess a source file
src/executing/user-api.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/executing/user-api.c.i
.PHONY : src/executing/user-api.c.i

src/executing/user-api.s: src/executing/user-api.c.s
.PHONY : src/executing/user-api.s

# target to generate assembly for a file
src/executing/user-api.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/executing/user-api.c.s
.PHONY : src/executing/user-api.c.s

src/opcodes/au/add.o: src/opcodes/au/add.c.o
.PHONY : src/opcodes/au/add.o

# target to build an object file
src/opcodes/au/add.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/au/add.c.o
.PHONY : src/opcodes/au/add.c.o

src/opcodes/au/add.i: src/opcodes/au/add.c.i
.PHONY : src/opcodes/au/add.i

# target to preprocess a source file
src/opcodes/au/add.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/au/add.c.i
.PHONY : src/opcodes/au/add.c.i

src/opcodes/au/add.s: src/opcodes/au/add.c.s
.PHONY : src/opcodes/au/add.s

# target to generate assembly for a file
src/opcodes/au/add.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/au/add.c.s
.PHONY : src/opcodes/au/add.c.s

src/opcodes/au/div.o: src/opcodes/au/div.c.o
.PHONY : src/opcodes/au/div.o

# target to build an object file
src/opcodes/au/div.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/au/div.c.o
.PHONY : src/opcodes/au/div.c.o

src/opcodes/au/div.i: src/opcodes/au/div.c.i
.PHONY : src/opcodes/au/div.i

# target to preprocess a source file
src/opcodes/au/div.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/au/div.c.i
.PHONY : src/opcodes/au/div.c.i

src/opcodes/au/div.s: src/opcodes/au/div.c.s
.PHONY : src/opcodes/au/div.s

# target to generate assembly for a file
src/opcodes/au/div.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/au/div.c.s
.PHONY : src/opcodes/au/div.c.s

src/opcodes/au/mul.o: src/opcodes/au/mul.c.o
.PHONY : src/opcodes/au/mul.o

# target to build an object file
src/opcodes/au/mul.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/au/mul.c.o
.PHONY : src/opcodes/au/mul.c.o

src/opcodes/au/mul.i: src/opcodes/au/mul.c.i
.PHONY : src/opcodes/au/mul.i

# target to preprocess a source file
src/opcodes/au/mul.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/au/mul.c.i
.PHONY : src/opcodes/au/mul.c.i

src/opcodes/au/mul.s: src/opcodes/au/mul.c.s
.PHONY : src/opcodes/au/mul.s

# target to generate assembly for a file
src/opcodes/au/mul.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/au/mul.c.s
.PHONY : src/opcodes/au/mul.c.s

src/opcodes/au/sub.o: src/opcodes/au/sub.c.o
.PHONY : src/opcodes/au/sub.o

# target to build an object file
src/opcodes/au/sub.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/au/sub.c.o
.PHONY : src/opcodes/au/sub.c.o

src/opcodes/au/sub.i: src/opcodes/au/sub.c.i
.PHONY : src/opcodes/au/sub.i

# target to preprocess a source file
src/opcodes/au/sub.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/au/sub.c.i
.PHONY : src/opcodes/au/sub.c.i

src/opcodes/au/sub.s: src/opcodes/au/sub.c.s
.PHONY : src/opcodes/au/sub.s

# target to generate assembly for a file
src/opcodes/au/sub.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/au/sub.c.s
.PHONY : src/opcodes/au/sub.c.s

src/opcodes/base/getreg.o: src/opcodes/base/getreg.c.o
.PHONY : src/opcodes/base/getreg.o

# target to build an object file
src/opcodes/base/getreg.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/base/getreg.c.o
.PHONY : src/opcodes/base/getreg.c.o

src/opcodes/base/getreg.i: src/opcodes/base/getreg.c.i
.PHONY : src/opcodes/base/getreg.i

# target to preprocess a source file
src/opcodes/base/getreg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/base/getreg.c.i
.PHONY : src/opcodes/base/getreg.c.i

src/opcodes/base/getreg.s: src/opcodes/base/getreg.c.s
.PHONY : src/opcodes/base/getreg.s

# target to generate assembly for a file
src/opcodes/base/getreg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/base/getreg.c.s
.PHONY : src/opcodes/base/getreg.c.s

src/opcodes/base/setreg.o: src/opcodes/base/setreg.c.o
.PHONY : src/opcodes/base/setreg.o

# target to build an object file
src/opcodes/base/setreg.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/base/setreg.c.o
.PHONY : src/opcodes/base/setreg.c.o

src/opcodes/base/setreg.i: src/opcodes/base/setreg.c.i
.PHONY : src/opcodes/base/setreg.i

# target to preprocess a source file
src/opcodes/base/setreg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/base/setreg.c.i
.PHONY : src/opcodes/base/setreg.c.i

src/opcodes/base/setreg.s: src/opcodes/base/setreg.c.s
.PHONY : src/opcodes/base/setreg.s

# target to generate assembly for a file
src/opcodes/base/setreg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/base/setreg.c.s
.PHONY : src/opcodes/base/setreg.c.s

src/opcodes/bits/and.o: src/opcodes/bits/and.c.o
.PHONY : src/opcodes/bits/and.o

# target to build an object file
src/opcodes/bits/and.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/bits/and.c.o
.PHONY : src/opcodes/bits/and.c.o

src/opcodes/bits/and.i: src/opcodes/bits/and.c.i
.PHONY : src/opcodes/bits/and.i

# target to preprocess a source file
src/opcodes/bits/and.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/bits/and.c.i
.PHONY : src/opcodes/bits/and.c.i

src/opcodes/bits/and.s: src/opcodes/bits/and.c.s
.PHONY : src/opcodes/bits/and.s

# target to generate assembly for a file
src/opcodes/bits/and.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/bits/and.c.s
.PHONY : src/opcodes/bits/and.c.s

src/opcodes/bits/not.o: src/opcodes/bits/not.c.o
.PHONY : src/opcodes/bits/not.o

# target to build an object file
src/opcodes/bits/not.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/bits/not.c.o
.PHONY : src/opcodes/bits/not.c.o

src/opcodes/bits/not.i: src/opcodes/bits/not.c.i
.PHONY : src/opcodes/bits/not.i

# target to preprocess a source file
src/opcodes/bits/not.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/bits/not.c.i
.PHONY : src/opcodes/bits/not.c.i

src/opcodes/bits/not.s: src/opcodes/bits/not.c.s
.PHONY : src/opcodes/bits/not.s

# target to generate assembly for a file
src/opcodes/bits/not.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/bits/not.c.s
.PHONY : src/opcodes/bits/not.c.s

src/opcodes/bits/or.o: src/opcodes/bits/or.c.o
.PHONY : src/opcodes/bits/or.o

# target to build an object file
src/opcodes/bits/or.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/bits/or.c.o
.PHONY : src/opcodes/bits/or.c.o

src/opcodes/bits/or.i: src/opcodes/bits/or.c.i
.PHONY : src/opcodes/bits/or.i

# target to preprocess a source file
src/opcodes/bits/or.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/bits/or.c.i
.PHONY : src/opcodes/bits/or.c.i

src/opcodes/bits/or.s: src/opcodes/bits/or.c.s
.PHONY : src/opcodes/bits/or.s

# target to generate assembly for a file
src/opcodes/bits/or.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/bits/or.c.s
.PHONY : src/opcodes/bits/or.c.s

src/opcodes/bits/xor.o: src/opcodes/bits/xor.c.o
.PHONY : src/opcodes/bits/xor.o

# target to build an object file
src/opcodes/bits/xor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/bits/xor.c.o
.PHONY : src/opcodes/bits/xor.c.o

src/opcodes/bits/xor.i: src/opcodes/bits/xor.c.i
.PHONY : src/opcodes/bits/xor.i

# target to preprocess a source file
src/opcodes/bits/xor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/bits/xor.c.i
.PHONY : src/opcodes/bits/xor.c.i

src/opcodes/bits/xor.s: src/opcodes/bits/xor.c.s
.PHONY : src/opcodes/bits/xor.s

# target to generate assembly for a file
src/opcodes/bits/xor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/bits/xor.c.s
.PHONY : src/opcodes/bits/xor.c.s

src/opcodes/copy/copy.o: src/opcodes/copy/copy.c.o
.PHONY : src/opcodes/copy/copy.o

# target to build an object file
src/opcodes/copy/copy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/copy/copy.c.o
.PHONY : src/opcodes/copy/copy.c.o

src/opcodes/copy/copy.i: src/opcodes/copy/copy.c.i
.PHONY : src/opcodes/copy/copy.i

# target to preprocess a source file
src/opcodes/copy/copy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/copy/copy.c.i
.PHONY : src/opcodes/copy/copy.c.i

src/opcodes/copy/copy.s: src/opcodes/copy/copy.c.s
.PHONY : src/opcodes/copy/copy.s

# target to generate assembly for a file
src/opcodes/copy/copy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/copy/copy.c.s
.PHONY : src/opcodes/copy/copy.c.s

src/opcodes/jmp/call.o: src/opcodes/jmp/call.c.o
.PHONY : src/opcodes/jmp/call.o

# target to build an object file
src/opcodes/jmp/call.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/jmp/call.c.o
.PHONY : src/opcodes/jmp/call.c.o

src/opcodes/jmp/call.i: src/opcodes/jmp/call.c.i
.PHONY : src/opcodes/jmp/call.i

# target to preprocess a source file
src/opcodes/jmp/call.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/jmp/call.c.i
.PHONY : src/opcodes/jmp/call.c.i

src/opcodes/jmp/call.s: src/opcodes/jmp/call.c.s
.PHONY : src/opcodes/jmp/call.s

# target to generate assembly for a file
src/opcodes/jmp/call.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/jmp/call.c.s
.PHONY : src/opcodes/jmp/call.c.s

src/opcodes/jmp/eif.o: src/opcodes/jmp/eif.c.o
.PHONY : src/opcodes/jmp/eif.o

# target to build an object file
src/opcodes/jmp/eif.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/jmp/eif.c.o
.PHONY : src/opcodes/jmp/eif.c.o

src/opcodes/jmp/eif.i: src/opcodes/jmp/eif.c.i
.PHONY : src/opcodes/jmp/eif.i

# target to preprocess a source file
src/opcodes/jmp/eif.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/jmp/eif.c.i
.PHONY : src/opcodes/jmp/eif.c.i

src/opcodes/jmp/eif.s: src/opcodes/jmp/eif.c.s
.PHONY : src/opcodes/jmp/eif.s

# target to generate assembly for a file
src/opcodes/jmp/eif.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/jmp/eif.c.s
.PHONY : src/opcodes/jmp/eif.c.s

src/opcodes/jmp/jif.o: src/opcodes/jmp/jif.c.o
.PHONY : src/opcodes/jmp/jif.o

# target to build an object file
src/opcodes/jmp/jif.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/jmp/jif.c.o
.PHONY : src/opcodes/jmp/jif.c.o

src/opcodes/jmp/jif.i: src/opcodes/jmp/jif.c.i
.PHONY : src/opcodes/jmp/jif.i

# target to preprocess a source file
src/opcodes/jmp/jif.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/jmp/jif.c.i
.PHONY : src/opcodes/jmp/jif.c.i

src/opcodes/jmp/jif.s: src/opcodes/jmp/jif.c.s
.PHONY : src/opcodes/jmp/jif.s

# target to generate assembly for a file
src/opcodes/jmp/jif.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/jmp/jif.c.s
.PHONY : src/opcodes/jmp/jif.c.s

src/opcodes/jmp/jifn.o: src/opcodes/jmp/jifn.c.o
.PHONY : src/opcodes/jmp/jifn.o

# target to build an object file
src/opcodes/jmp/jifn.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/jmp/jifn.c.o
.PHONY : src/opcodes/jmp/jifn.c.o

src/opcodes/jmp/jifn.i: src/opcodes/jmp/jifn.c.i
.PHONY : src/opcodes/jmp/jifn.i

# target to preprocess a source file
src/opcodes/jmp/jifn.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/jmp/jifn.c.i
.PHONY : src/opcodes/jmp/jifn.c.i

src/opcodes/jmp/jifn.s: src/opcodes/jmp/jifn.c.s
.PHONY : src/opcodes/jmp/jifn.s

# target to generate assembly for a file
src/opcodes/jmp/jifn.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/jmp/jifn.c.s
.PHONY : src/opcodes/jmp/jifn.c.s

src/opcodes/jmp/jmp.o: src/opcodes/jmp/jmp.c.o
.PHONY : src/opcodes/jmp/jmp.o

# target to build an object file
src/opcodes/jmp/jmp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/jmp/jmp.c.o
.PHONY : src/opcodes/jmp/jmp.c.o

src/opcodes/jmp/jmp.i: src/opcodes/jmp/jmp.c.i
.PHONY : src/opcodes/jmp/jmp.i

# target to preprocess a source file
src/opcodes/jmp/jmp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/jmp/jmp.c.i
.PHONY : src/opcodes/jmp/jmp.c.i

src/opcodes/jmp/jmp.s: src/opcodes/jmp/jmp.c.s
.PHONY : src/opcodes/jmp/jmp.s

# target to generate assembly for a file
src/opcodes/jmp/jmp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/jmp/jmp.c.s
.PHONY : src/opcodes/jmp/jmp.c.s

src/opcodes/jmp/ret.o: src/opcodes/jmp/ret.c.o
.PHONY : src/opcodes/jmp/ret.o

# target to build an object file
src/opcodes/jmp/ret.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/jmp/ret.c.o
.PHONY : src/opcodes/jmp/ret.c.o

src/opcodes/jmp/ret.i: src/opcodes/jmp/ret.c.i
.PHONY : src/opcodes/jmp/ret.i

# target to preprocess a source file
src/opcodes/jmp/ret.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/jmp/ret.c.i
.PHONY : src/opcodes/jmp/ret.c.i

src/opcodes/jmp/ret.s: src/opcodes/jmp/ret.c.s
.PHONY : src/opcodes/jmp/ret.s

# target to generate assembly for a file
src/opcodes/jmp/ret.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/jmp/ret.c.s
.PHONY : src/opcodes/jmp/ret.c.s

src/opcodes/share/alc.o: src/opcodes/share/alc.c.o
.PHONY : src/opcodes/share/alc.o

# target to build an object file
src/opcodes/share/alc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/share/alc.c.o
.PHONY : src/opcodes/share/alc.c.o

src/opcodes/share/alc.i: src/opcodes/share/alc.c.i
.PHONY : src/opcodes/share/alc.i

# target to preprocess a source file
src/opcodes/share/alc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/share/alc.c.i
.PHONY : src/opcodes/share/alc.c.i

src/opcodes/share/alc.s: src/opcodes/share/alc.c.s
.PHONY : src/opcodes/share/alc.s

# target to generate assembly for a file
src/opcodes/share/alc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/share/alc.c.s
.PHONY : src/opcodes/share/alc.c.s

src/opcodes/share/ende.o: src/opcodes/share/ende.c.o
.PHONY : src/opcodes/share/ende.o

# target to build an object file
src/opcodes/share/ende.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/share/ende.c.o
.PHONY : src/opcodes/share/ende.c.o

src/opcodes/share/ende.i: src/opcodes/share/ende.c.i
.PHONY : src/opcodes/share/ende.i

# target to preprocess a source file
src/opcodes/share/ende.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/share/ende.c.i
.PHONY : src/opcodes/share/ende.c.i

src/opcodes/share/ende.s: src/opcodes/share/ende.c.s
.PHONY : src/opcodes/share/ende.s

# target to generate assembly for a file
src/opcodes/share/ende.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/share/ende.c.s
.PHONY : src/opcodes/share/ende.c.s

src/opcodes/share/mov.o: src/opcodes/share/mov.c.o
.PHONY : src/opcodes/share/mov.o

# target to build an object file
src/opcodes/share/mov.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/share/mov.c.o
.PHONY : src/opcodes/share/mov.c.o

src/opcodes/share/mov.i: src/opcodes/share/mov.c.i
.PHONY : src/opcodes/share/mov.i

# target to preprocess a source file
src/opcodes/share/mov.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/share/mov.c.i
.PHONY : src/opcodes/share/mov.c.i

src/opcodes/share/mov.s: src/opcodes/share/mov.c.s
.PHONY : src/opcodes/share/mov.s

# target to generate assembly for a file
src/opcodes/share/mov.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/share/mov.c.s
.PHONY : src/opcodes/share/mov.c.s

src/opcodes/share/prt.o: src/opcodes/share/prt.c.o
.PHONY : src/opcodes/share/prt.o

# target to build an object file
src/opcodes/share/prt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/share/prt.c.o
.PHONY : src/opcodes/share/prt.c.o

src/opcodes/share/prt.i: src/opcodes/share/prt.c.i
.PHONY : src/opcodes/share/prt.i

# target to preprocess a source file
src/opcodes/share/prt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/share/prt.c.i
.PHONY : src/opcodes/share/prt.c.i

src/opcodes/share/prt.s: src/opcodes/share/prt.c.s
.PHONY : src/opcodes/share/prt.s

# target to generate assembly for a file
src/opcodes/share/prt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/share/prt.c.s
.PHONY : src/opcodes/share/prt.c.s

src/opcodes/stack/pop.o: src/opcodes/stack/pop.c.o
.PHONY : src/opcodes/stack/pop.o

# target to build an object file
src/opcodes/stack/pop.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/stack/pop.c.o
.PHONY : src/opcodes/stack/pop.c.o

src/opcodes/stack/pop.i: src/opcodes/stack/pop.c.i
.PHONY : src/opcodes/stack/pop.i

# target to preprocess a source file
src/opcodes/stack/pop.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/stack/pop.c.i
.PHONY : src/opcodes/stack/pop.c.i

src/opcodes/stack/pop.s: src/opcodes/stack/pop.c.s
.PHONY : src/opcodes/stack/pop.s

# target to generate assembly for a file
src/opcodes/stack/pop.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/stack/pop.c.s
.PHONY : src/opcodes/stack/pop.c.s

src/opcodes/stack/push.o: src/opcodes/stack/push.c.o
.PHONY : src/opcodes/stack/push.o

# target to build an object file
src/opcodes/stack/push.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/stack/push.c.o
.PHONY : src/opcodes/stack/push.c.o

src/opcodes/stack/push.i: src/opcodes/stack/push.c.i
.PHONY : src/opcodes/stack/push.i

# target to preprocess a source file
src/opcodes/stack/push.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/stack/push.c.i
.PHONY : src/opcodes/stack/push.c.i

src/opcodes/stack/push.s: src/opcodes/stack/push.c.s
.PHONY : src/opcodes/stack/push.s

# target to generate assembly for a file
src/opcodes/stack/push.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/stack/push.c.s
.PHONY : src/opcodes/stack/push.c.s

src/opcodes/stub/panic.o: src/opcodes/stub/panic.c.o
.PHONY : src/opcodes/stub/panic.o

# target to build an object file
src/opcodes/stub/panic.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/stub/panic.c.o
.PHONY : src/opcodes/stub/panic.c.o

src/opcodes/stub/panic.i: src/opcodes/stub/panic.c.i
.PHONY : src/opcodes/stub/panic.i

# target to preprocess a source file
src/opcodes/stub/panic.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/stub/panic.c.i
.PHONY : src/opcodes/stub/panic.c.i

src/opcodes/stub/panic.s: src/opcodes/stub/panic.c.s
.PHONY : src/opcodes/stub/panic.s

# target to generate assembly for a file
src/opcodes/stub/panic.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delta_vm.dir/build.make CMakeFiles/delta_vm.dir/src/opcodes/stub/panic.c.s
.PHONY : src/opcodes/stub/panic.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... delta_vm"
	@echo "... src/executing/core-api.o"
	@echo "... src/executing/core-api.i"
	@echo "... src/executing/core-api.s"
	@echo "... src/executing/debug.o"
	@echo "... src/executing/debug.i"
	@echo "... src/executing/debug.s"
	@echo "... src/executing/exec.o"
	@echo "... src/executing/exec.i"
	@echo "... src/executing/exec.s"
	@echo "... src/executing/loader/check.o"
	@echo "... src/executing/loader/check.i"
	@echo "... src/executing/loader/check.s"
	@echo "... src/executing/loader/load.o"
	@echo "... src/executing/loader/load.i"
	@echo "... src/executing/loader/load.s"
	@echo "... src/executing/sym.o"
	@echo "... src/executing/sym.i"
	@echo "... src/executing/sym.s"
	@echo "... src/executing/user-api.o"
	@echo "... src/executing/user-api.i"
	@echo "... src/executing/user-api.s"
	@echo "... src/opcodes/au/add.o"
	@echo "... src/opcodes/au/add.i"
	@echo "... src/opcodes/au/add.s"
	@echo "... src/opcodes/au/div.o"
	@echo "... src/opcodes/au/div.i"
	@echo "... src/opcodes/au/div.s"
	@echo "... src/opcodes/au/mul.o"
	@echo "... src/opcodes/au/mul.i"
	@echo "... src/opcodes/au/mul.s"
	@echo "... src/opcodes/au/sub.o"
	@echo "... src/opcodes/au/sub.i"
	@echo "... src/opcodes/au/sub.s"
	@echo "... src/opcodes/base/getreg.o"
	@echo "... src/opcodes/base/getreg.i"
	@echo "... src/opcodes/base/getreg.s"
	@echo "... src/opcodes/base/setreg.o"
	@echo "... src/opcodes/base/setreg.i"
	@echo "... src/opcodes/base/setreg.s"
	@echo "... src/opcodes/bits/and.o"
	@echo "... src/opcodes/bits/and.i"
	@echo "... src/opcodes/bits/and.s"
	@echo "... src/opcodes/bits/not.o"
	@echo "... src/opcodes/bits/not.i"
	@echo "... src/opcodes/bits/not.s"
	@echo "... src/opcodes/bits/or.o"
	@echo "... src/opcodes/bits/or.i"
	@echo "... src/opcodes/bits/or.s"
	@echo "... src/opcodes/bits/xor.o"
	@echo "... src/opcodes/bits/xor.i"
	@echo "... src/opcodes/bits/xor.s"
	@echo "... src/opcodes/copy/copy.o"
	@echo "... src/opcodes/copy/copy.i"
	@echo "... src/opcodes/copy/copy.s"
	@echo "... src/opcodes/jmp/call.o"
	@echo "... src/opcodes/jmp/call.i"
	@echo "... src/opcodes/jmp/call.s"
	@echo "... src/opcodes/jmp/eif.o"
	@echo "... src/opcodes/jmp/eif.i"
	@echo "... src/opcodes/jmp/eif.s"
	@echo "... src/opcodes/jmp/jif.o"
	@echo "... src/opcodes/jmp/jif.i"
	@echo "... src/opcodes/jmp/jif.s"
	@echo "... src/opcodes/jmp/jifn.o"
	@echo "... src/opcodes/jmp/jifn.i"
	@echo "... src/opcodes/jmp/jifn.s"
	@echo "... src/opcodes/jmp/jmp.o"
	@echo "... src/opcodes/jmp/jmp.i"
	@echo "... src/opcodes/jmp/jmp.s"
	@echo "... src/opcodes/jmp/ret.o"
	@echo "... src/opcodes/jmp/ret.i"
	@echo "... src/opcodes/jmp/ret.s"
	@echo "... src/opcodes/share/alc.o"
	@echo "... src/opcodes/share/alc.i"
	@echo "... src/opcodes/share/alc.s"
	@echo "... src/opcodes/share/ende.o"
	@echo "... src/opcodes/share/ende.i"
	@echo "... src/opcodes/share/ende.s"
	@echo "... src/opcodes/share/mov.o"
	@echo "... src/opcodes/share/mov.i"
	@echo "... src/opcodes/share/mov.s"
	@echo "... src/opcodes/share/prt.o"
	@echo "... src/opcodes/share/prt.i"
	@echo "... src/opcodes/share/prt.s"
	@echo "... src/opcodes/stack/pop.o"
	@echo "... src/opcodes/stack/pop.i"
	@echo "... src/opcodes/stack/pop.s"
	@echo "... src/opcodes/stack/push.o"
	@echo "... src/opcodes/stack/push.i"
	@echo "... src/opcodes/stack/push.s"
	@echo "... src/opcodes/stub/panic.o"
	@echo "... src/opcodes/stub/panic.i"
	@echo "... src/opcodes/stub/panic.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

